"use client";

import type { ReportData } from "@/types/report";
import { Disclaimer } from "@/components/ui/Disclaimer";
import { ReportHeader } from "./ReportHeader";
import { TaxSection } from "./TaxSection";
import { BASSection } from "./BASSection";
import { DeductionsSection } from "./DeductionsSection";
import { BusinessDeductionsSection } from "./BusinessDeductionsSection";
import { DebtSection } from "./DebtSection";
import { BenefitsSection } from "./BenefitsSection";
import { ActionChecklist } from "./ActionChecklist";
import { DiscoveriesSection } from "./DiscoveriesSection";
import { ShareReport } from "./ShareReport";
import { SupportBanner } from "./SupportBanner";

type ReportViewProps = {
  data: ReportData;
  onReset: () => void;
};

export function ReportView({ data, onReset }: ReportViewProps) {
  const showBAS = data.bas.required;
  const showDebt = data.debt.priorityOrder.length > 0;
  const showDiscoveries = data.discoveries.items.length > 0;
  const showBusinessDeductions =
    data.businessDeductions?.applicable === true;

  return (
    <div data-testid="report-view">
      <ReportHeader />

      <div className="space-y-12">
        {/* Discoveries - the hero section, shown first */}
        {showDiscoveries && <DiscoveriesSection data={data.discoveries} />}

        {/* Tax - always shown */}
        <TaxSection data={data.tax} />

        {/* BAS - conditional */}
        {showBAS && <BASSection data={data.bas} />}

        {/* Deductions - always shown */}
        <DeductionsSection data={data.deductions} />

        {/* Business Deductions - conditional on being a business owner */}
        {showBusinessDeductions && data.businessDeductions && (
          <BusinessDeductionsSection data={data.businessDeductions} />
        )}

        {/* Debt - conditional on having debt data */}
        {showDebt && <DebtSection data={data.debt} />}

        {/* Benefits - component handles empty state internally */}
        <BenefitsSection data={data.benefits} />

        {/* Action checklist */}
        <ActionChecklist data={data.actions} />

        {/* Share / print / reset */}
        <ShareReport data={data} onReset={onReset} />

        {/* Support / donate */}
        <SupportBanner />

        {/* Final disclaimer */}
        <Disclaimer
          text="This report was generated by AI based on the information you provided and current ATO rates. It is general information only and is not financial, tax, or legal advice. Always verify figures with the ATO or a registered tax professional before making financial decisions."
        />
      </div>
    </div>
  );
}
