"use client";

import { useState, useCallback } from "react";
import type { ReportData } from "@/types/report";
import { Button } from "@/components/ui/Button";

type ShareReportProps = {
  data: ReportData;
  onReset: () => void;
};

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-AU", {
    style: "currency",
    currency: "AUD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}

function buildSummaryText(data: ReportData): string {
  const lines: string[] = [
    "Sorted - Your Financial Summary (2025-26)",
    "",
    `Tax set-aside: ${formatCurrency(data.tax.fortnightlySetAside)}/fortnight`,
    `Annual tax estimate: ${formatCurrency(data.tax.annualTaxEstimate)}`,
    `Medicare levy: ${formatCurrency(data.tax.medicareLevy)}`,
  ];

  if (data.tax.hecsRepayment > 0) {
    lines.push(
      `HECS-HELP repayment: ${formatCurrency(data.tax.hecsRepayment)}`
    );
  }

  lines.push("");

  if (data.deductions.totalEstimatedDeductions > 0) {
    lines.push(
      `Estimated deductions: ${formatCurrency(data.deductions.totalEstimatedDeductions)}`
    );
  }

  if (data.bas.required) {
    lines.push(`BAS frequency: ${data.bas.frequency}`);
    lines.push(`Next BAS due: ${data.bas.nextDueDate}`);
  }

  if (data.debt.priorityOrder.length > 0) {
    lines.push("");
    lines.push(`Debt strategy: ${data.debt.strategy}`);
  }

  lines.push("");
  lines.push(
    "Generated by Sorted (getsorted.au) - General information only, not financial advice."
  );

  return lines.join("\n");
}

export function ShareReport({ data, onReset }: ShareReportProps) {
  const [copied, setCopied] = useState(false);

  const handlePrint = useCallback(() => {
    window.print();
  }, []);

  const handleCopy = useCallback(async () => {
    const text = buildSummaryText(data);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = text;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [data]);

  return (
    <div className="no-print flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
      <Button variant="secondary" onClick={handlePrint}>
        <svg
          className="h-4 w-4"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={2}
          stroke="currentColor"
          aria-hidden="true"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18 10.5h.008v.008H18V10.5zm-3 0h.008v.008H15V10.5z"
          />
        </svg>
        Print this report
      </Button>

      <Button variant="secondary" onClick={handleCopy}>
        {copied ? (
          <>
            <svg
              className="h-4 w-4 text-green"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={2}
              stroke="currentColor"
              aria-hidden="true"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M4.5 12.75l6 6 9-13.5"
              />
            </svg>
            Copied
          </>
        ) : (
          <>
            <svg
              className="h-4 w-4"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={2}
              stroke="currentColor"
              aria-hidden="true"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9.75a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184"
              />
            </svg>
            Copy summary
          </>
        )}
      </Button>

      <Button variant="outline" onClick={onReset}>
        <svg
          className="h-4 w-4"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={2}
          stroke="currentColor"
          aria-hidden="true"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.992 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182"
          />
        </svg>
        Start over
      </Button>
    </div>
  );
}
